import React from 'react';
import Footer from '../layout/Footer';

function Terms() {
  return (
    <>
      <header className="container1">
        <div className="img"></div>
        <div className="overlay"></div>
        <div className="text text-center">
          <p>Terms of Service</p>
        </div>
      </header>

      <div className="container py-5">
        <div>
          <p>Last Updated: June 1, 2020</p>
          <p>
            <b>
              <i>
                PLEASE CAREFULLY READ THESE TERMS AND CONDITIONS OF USE BEFORE
                USING THIS SITE OR ANY OF THE SERVICES AND APPLICATIONS
              </i>
            </b>
          </p>
          <ol>
            <li>
              <b>Contractual Relationship</b>
              <br />
              <br />
              <p>
                The terms and conditions (“Agreement”) apply to Arena Laundry’s
                website (arena-laundry.com), the related mobile application
                and/or selected other domains, existing or future, content,
                products and services (collectively, the “Services”). As used in
                this Agreement, “we,” “us,” or “our” shall mean Arena Laundry.
              </p>
              <p>
                By accessing or using our Services, whether or not you register,
                you agree to the terms of this Agreement and to the collection,
                use and disclosure of your information as set forth in our
                Privacy Policy, which establish a contractual relationship
                between you and Arena Laundry. This Agreement supersedes prior
                agreements or arrangements with you. You should review the
                Agreement before providing us with any information.
              </p>
              <p>
                <b className="text-decoration-underline">
                  If you do not agree with this Agreement please do not access
                  or use our Services.
                </b>
              </p>
              <p>
                As a condition to this Agreement you acknowledge that we may, in
                our sole discretion modify this Agreement at any time. All
                modifications will be effective immediately upon posting. If you
                continue to use the service after the posting of any and all
                modifications constitutes your consent to the changes. You are
                responsible to review this Agreement from time to time so that
                you are aware of any and all changes to the Agreement.
              </p>
            </li>
            <li>
              <b>The Services</b>
              <br />
              <br />
              <p>
                Arena Laundry is a weekly laundry service that enables users to
                schedule the delivery using the Arena Laundry website and/or
                mobile applications (collectively, the “Applications”). After
                scheduling service using the Application, Arena Laundry will
                clean the clothing.
              </p>
              <p>
                <b className="text-decoration-underline">
                  Ownership, Service Terms and Limitations
                </b>
              </p>
              <p>
                Proprietary Rights. The Services, including but not limited to,
                the text, content, photographs, images, audio, graphics, and any
                software (which includes any files or images incorporated in or
                generated by the software) available on the Services are owned
                and operated by Arena Laundry.
              </p>
              <p>
                The Services and related materials (“Materials”) are protected
                by copyright, trademark, domain name, trade dress, domain name,
                patent, trade secret, international treaties and/or other
                proprietary rights and laws of the United States and other
                countries. Except as otherwise indicated in the Services and
                except for the trademarks, service marks and trade names of
                other companies that are or may be displayed in the Services,
                all trademarks, service marks and trade names are owned by Arena
                Laundry.
              </p>
              <p>
                By accessing and using the Services, you acknowledge and agree
                to abide by all applicable intellectual property laws, as well
                as any additional notices or restrictions contained in this
                Agreement.
              </p>
              <p>
                You are allowed to display and, subject to any expressly stated
                restrictions or limitations relating to specific material,
                download portions of the Services only for non-commercial use,
                unless otherwise permitted. Any redistribution, retransmission
                or publication of any copyrighted material is strictly
                prohibited without the express written permission of the
                copyright owner. You may not change or delete any proprietary
                notices from materials downloaded from the Services. You agree
                not to use any Arena Laundry logo or any other proprietary
                graphic or trademark without Arena Laundry’s express written
                consent. As between the parties, title, ownership rights, and
                intellectual property rights in the Services, and any copies or
                portions thereof, shall remain in Arena Laundry and/or its
                content providers. Third-party trademarks, service marks and
                logos contained in the Site are owned and licensed by their
                respective owners. Any and all rights not expressly granted
                herein are reserved.
              </p>
              <p>
                <b className="text-decoration-underline">
                  Grant of Limited License
                </b>
              </p>
              <p>
                Subject to your compliance with the terms of the Agreement,
                Arena Laundry grants you a limited, non-exclusive,
                non-sub-licensable, revocable, non-transferrable license to: (i)
                access and use the Applications on your personal device solely
                in connection with your use of the Services; and (ii) access and
                use any content, information and related Materials that may be
                made available through the Services, in each case solely for
                your personal, noncommercial use. Any rights not expressly
                granted herein are reserved by Arena Laundry and Arena Laundry’s
                licensors.
              </p>
              <p>
                Nothing contained in the Services should be construed as
                granting, by implication, estoppel or otherwise, any license or
                right to use any of the Materials or proprietary content without
                the express written permission of Arena Laundry or such other
                party as may own the proprietary rights.
              </p>
            </li>
            <li>
              <b>Use of Services</b>
              <br />
              <br />
              <p>
                <b className="text-decoration-underline">
                  User Requirements and Conduct
                </b>
              </p>
              <p>
                In order to use most aspects of the Services, you must register
                for and maintain an active personal user Services account
                (“Account”). You must be at least 13 years of age to obtain an
                Account. Account registration requires you to submit to Arena
                Laundry certain personal information, such as your name, address
                and mobile phone number, as well as at least one valid credit
                card. You agree to maintain accurate, complete, and up-to-date
                information in your Account, review the fees to be charged for
                your use of the Services; and authorize Arena Laundry and its
                affiliates to charge your Credit Card for any and all Fees
                incurred by you for your use of the Services. Your failure to
                maintain accurate, complete, and up-to-date Account information,
                including having an invalid or expired credit card on file, may
                result in your inability to access and use the Services or Arena
                Laundry termination of this Agreement with you. You are
                responsible for all activity that occurs under your Account,
                and, as such, you agree to maintain the security and secrecy of
                your Account username and password at all times. Unless
                otherwise permitted by Arena Laundry in writing, you may only
                possess one Account per household.
              </p>
              <p>
                The Service is not available for use by persons under the age of
                13. You may not authorize third parties to use your Account, and
                you may not allow persons under the age of 13 to use the
                Services unless they are accompanied by you. You may not assign
                or otherwise transfer your Account to any other person or
                entity. You agree to comply with all applicable laws when using
                the Services, and you may only use the Services for lawful
                purposes. In certain instances Arena Laundry or a Third Party
                Contractor may require you to provide proof of identity to
                access or use the Services, and you agree that you may be denied
                access or use of the Services if you refuse to provide proof of
                identity.
              </p>
              <p>
                <b className="text-decoration-underline">
                  User Representations
                </b>
              </p>
              <p>
                You represent and warrant to Arena Laundry that you will (a)
                maintain the security of your user identification, password and
                other confidential information relating to your Account; (b)
                maintain the security, confidentiality and integrity of all
                messages and the content that you receive, transmit through or
                store on the Service; (c) maintain all charges resulting from
                the use of your Account, including but not limited to,
                unauthorized use of your Account prior to you notifying Arena
                Laundry in writing of such use and taking steps to prevent its
                further occurrence by changing your password; (d) comply with
                the Terms of Service set forth herein; and (e) comply with all
                applicable U.S. and international laws, statutes, ordinances,
                rules, regulations, contracts and applicable licenses regarding
                your use of the Services or Site.
              </p>
              <p>
                <b className="text-decoration-underline">
                  User Restrictions and Promotional Offers and Special Offers
                </b>
              </p>
              <p>
                You are not permitted, directly or indirectly, to (i) engage in
                any acts inconsistent with the principles of copyright
                protection and fair use, as codified in 17 U.S.C. Sections
                106-110, without obtaining the express written consent of Arena
                Laundry and/or the copyright owner; or (ii) submit content or
                information that is purposely inaccurate, commits fraud or
                falsifies information in connection with your Account or to
                create multiple Accounts. Arena Laundry may, in our sole
                discretion, create promotional codes that may be redeemed for
                Service credit or other features or benefits, subject to the
                terms that Arena Laundry may establish on a per promotional
                basis. You agree that promotional codes (i) must be used for the
                intended audience and purpose, (ii) may not be duplicated, sold,
                or transferred in any manner or made available to the general
                public, unless explicitly approved by Arena Laundry in writing
                (iii) exceed or attempt to exceed quantity limits when
                purchasing offerings or promotions or otherwise using any
                Account to purchase offerings or promotions for resale or for
                speculative, false, fraudulent or any other purpose not
                expressly permitted by the terms of this Agreement and the terms
                of a specific offer on the Services. All promotional codes (i)
                may be disabled by Arena Laundry at any time for any reason
                without liability to Arena Laundry; (ii) are not valid for cash;
                and (iii) may expire prior to your use.
              </p>
              <p>
                Arena Laundry reserves the right to withhold or deduct credits
                or other features or benefits obtained through the use of
                promotional offer by you or any other user in the event that
                Arena Laundry determines or believes that the use or redemption
                of the promotion offer was in error, fraudulent, illegal, or in
                violation of the applicable promotional offer terms or these
                Terms. Arena Laundry shall pursue and prosecute to the fullest
                extent of the law any case of misrepresentation, fraud or known
                or potential violations of the law or terms of this Agreement.
              </p>
              <p>
                <b className="text-decoration-underline">Text Messages</b>
              </p>
              <p>
                By creating an Account, you agree that the Services may send you
                informational text (SMS) messages as part of the normal business
                operation of your use of the Services. You may opt-out of
                receiving text (SMS) messages from Arena Laundry at any time by
                sending a request to help@arena-laundry.com. You acknowledge
                that opting out of receiving text (SMS) messages may impact your
                use of the Services.
              </p>
              <p>
                <b className="text-decoration-underline">
                  Damaged or Lost Items
                </b>
              </p>
              <p>Damaged Items</p>
              <p>
                Arena Laundry follows the standards and policies set forth by
                the Fabricare Industry and the International Fabricare
                Institute. We exercise utmost care in cleaning and processing
                garments entrusted to us and use such processes, which, in our
                opinion, are best suited to the nature and conditions of each
                individual garment. Nevertheless, we cannot assume
                responsibility for inherent weaknesses or defects in materials
                which may result in tears or development of small holes in
                fabric that are not readily apparent prior to processing. We
                cannot guarantee against color loss, color bleeding, shrinkage,
                or against damage to weak and tender fabrics.
              </p>
              <p>
                Although, we try as hard as possible to track such items, we are
                not responsible for loose items in pockets or bundles of
                garments (i.e. jewelry, watches, cash). We request that
                customers empty pockets prior to putting laundry out for pickup
                as we can not be held responsible for damage to your garments
                from items left in pockets (lipstick, gum, pens, etc.). Arena
                Laundry liability with respect to any damaged items shall not
                exceed ten (10) times our charge for cleaning that garment
                regardless of brand or condition.
              </p>
              <p>
                Arena Laundry will not be responsible for any reparation beyond
                $50.00, even if the order costs over $10.00 to process. Any
                single item will not be valued beyond $25.00 for reimbursement.
              </p>
              <p>Lost Items</p>
              <p>
                Please report any missing items from your order to
                help@arena-laundry.com within 24 hours of delivery. Arena
                Laundry is not responsible for any missing items reported after
                this time.
              </p>
              <p>
                <b className="text-decoration-underline">
                  Pick-Up and Delivery
                </b>
              </p>
              <p>
                Our goal is to provide a convenient and frictionless service to
                our customers and are willing to leave orders wherever the
                customer dictates. However, Arena Laundry is not responsible for
                any items if the order was not personally received and
                personally delivered to and from an Arena Laundry employee.
                Arena Laundry is not responsible for missing items from orders
                that are picked up or dropped off in an unsecured or unattended
                location.
              </p>
              <p>
                <b className="text-decoration-underline">
                  Online Communications
                </b>
              </p>
              <p>
                We may provide interactive opportunities in the Services,
                including, without limitation, user ratings and reviews, saved
                favorites and saved instructions, (collectively, “Interactive
                Areas”) for the enjoyment of our users.
              </p>
              <p>
                You represent and warrant that you are the owner or otherwise
                have the right to provide any information, comments, reviews,
                ratings or other materials or content submitted, posted or
                otherwise transmitted to the Services (“User Content”). In
                addition, in consideration of the Services accepting User
                Content, you hereby grant to Arena Laundry an irrevocable,
                transferable, paid up, royalty-free, perpetual, non-exclusive
                worldwide sub-licensable license to use, copy, print, display,
                modify, edit, remove, publicly perform, translate and create
                derivative works from and distribute or otherwise use and
                reproduce User Content on the Services and in all forms of media
                now known or hereafter invented, including but not limited to
                such uses as on and in the Services throughout the world in all
                forms of media now known or hereafter invented in perpetuity
                (collectively, the “Uses”) and the right to, in Arena Laundry’s
                sole option and discretion, attribute such User Content to the
                user submitting the User Content. In consideration of submitting
                User Content, you consent to the Uses of the User Content
                without further consideration, compensation, attribution,
                notification or other additional consideration and to Arena
                Laundry’s disclosure of any information related to your use of
                the Services in any capacity in connection with Arena Laundry’s
                display of your User Content on the Services. You also agree to
                indemnify and hold Arena Laundry harmless from any claim or
                demand, including reasonable attorneys’ fees, made by any party
                arising out of the Uses of the User Content that you submit on
                our Services. You waive any rights you may have in having the
                User Content edited, altered or changed in any manner not
                acceptable to you.
              </p>
              <p>
                Some submissions or postings by users to certain parts of the
                Services, including, without limitation, Interactive Areas, will
                be public and posted in public areas on our Services. Arena
                Laundry and any contract or operational providers that conduct,
                operate and/or manage any portion of the Services will not be
                responsible for the action of any users or third parties with
                respect to any information, materials or content posted,
                uploaded or transmitted on the Services.
              </p>
              <p>
                By participating in any of the aforementioned activities, all
                users agree to follow the Services standards of conduct. Arena
                Laundry reserve the right to change, delete or remove, in part
                or in full, any postings in Interactive Areas and to terminate
                or suspend access to such areas of the Services for conduct that
                we believe, in our sole discretion, interferes with other
                peoples’ enjoyment of our Services. Arena Laundry will also
                cooperate with local, state and/or federal authorities to comply
                with applicable law.
              </p>
              <p>
                <b className="text-decoration-underline">
                  No Unlawful or Prohibited Use / Monitoring of Services
                </b>
              </p>
              <p>
                By using and accessing the Services, you agree that you will not
                use the Services for any unlawful purpose or engage in any use
                prohibited by this Agreement. You further agree that you will
                not use the Services in any manner that could damage, disable,
                overburden or impair any Arena Laundry server, or the network(s)
                connected to any Arena Laundry server, or interfere with any
                other party’s use and enjoyment of the Services. You may not
                attempt, through any means, to gain unauthorized access to any
                part of the Services, other account, computer system or network
                connected to any Arena Laundry server. Arena Laundry reserves
                the right, in its sole discretion, to monitor any and all use of
                the Services.Violators of the Agreement
              </p>
              <p>
                Arena Laundry reserves the right to seek all remedies available
                at law and in equity for violations of the Agreement, including
                the right to block access from a particular Internet address to
                the Services.
              </p>
            </li>
            <li>
              <b>Payment</b>
              <br />
              <br />
              <p>
                You understand that use of the Services may result in payments
                by you for the services you receive (“Charges”). When signing
                up, Arena Laundry will process payment of the applicable
                Charges, using the preferred payment method designated in your
                Account.
              </p>
              <p>
                Charges will be inclusive of applicable taxes where required by
                law. Charges paid by you are final and non-refundable, unless
                otherwise determined by Arena Laundry. Any request for lower
                Charges or disagreement with the Charges should be addressed to
                Arena Laundry by contacting help@arena-laundry.com.
              </p>
              <p>
                We reserve the right to establish, remove and/or revise Charges
                for any or all aspects of the Services at any time in our sole
                discretion.
              </p>
              <p>
                Arena Laundry may from time to time provide certain users with
                promotional offers and discounts that may result in different
                Charges for the same or similar Services, and you agree that
                such promotional offers and discounts, unless also made
                available to you, shall have no bearing on your use of the
                Services or the Charges applied to you.
              </p>
            </li>
            <li>
              <b>DISCLAIMERS, LIMITATIONS OF LIABILITY, INDEMNITY</b>
              <br />
              <br />
              <p>
                <b className="text-decoration-underline">DISCLAIMER</b>
              </p>
              <p>
                THE MATERIALS AND THE SERVICES ARE PROVIDED “AS IS” AND WITHOUT
                WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. TO THE FULLEST
                EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, Arena Laundry AND
                ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS OR REPRESENTATIVES
                DISCLAIM WITH RESPECT TO THE SERVICES AND THE MATERIALS HEREIN
                ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED
                TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
                PARTICULAR PURPOSE. IT IS STILL THE USER RESPOSIBILITY TO
                CAREFUL READ AND INSPECT ANY SERVICE OR PRODUCT YOU PURCHASE
                THROUGH OUR APPLICATIONS UPON YOUR RECEIPT TO DETERMINE SAEFTY
                AND APPRORPIATENESS FOR YOUR CONSUMPTION OR USE. WE DO NOT
                REPRESENT OR WARRANT THAT THE FUNCTIONS CONTAINED IN THE
                MATERIALS WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL
                BE CORRECTED, OR THAT THE SERVICES OR THE SERVER THAT MAKES IT
                AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. ARENA
                LAUNDRY DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING
                THE USE OF THE MATERIALS AND/OR THE SERVICES IN TERMS OF THEIR
                CORRECTNESS, ACCURACY, RELIABILITY, TIMELINESS, COMPLETENESS,
                CURRENTNESS, OR OTHERWISE. YOU (AND NOT ARENA LAUNDRY) ASSUME
                THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR, OR
                CORRECTION. APPLICABLE LAW MAY NOT ALLOW THE EXCLUSION OF
                IMPLIED WARRANTIES, SO THE ABOVE EXCLUSION MAY NOT APPLY TO YOU.
              </p>
              <p>
                <b className="text-decoration-underline">
                  LIMITATION OF LIABILITY
                </b>
              </p>
              <p>
                Under no circumstances, including, but not limited to,
                negligence, shall Arena Laundry or its officers, directors,
                employees, agents or representatives be liable to you or any
                third party for any special, consequential, incidental, direct,
                indirect, or punitive damages or any other loss or injury that
                result from the use of, or the inability to use, the Services or
                the Materials, even if Arena Laundry or an authorized
                representative has been advised of the possibility of such
                damages. In no event shall Arena Laundry have any liability for
                any damages, losses and other causes of action (whether in
                contract, tort (including, but not limited to, negligence), or
                otherwise for accessing or using the Services or engaging the
                services of or purchasing product(s) of a third party through or
                after accessing the Services.
              </p>
              <p>
                These limitations do not purport to limit liability that cannot
                be excluded under the law in the jurisdiction of this Agreement.
              </p>
              <p>
                <b className="text-decoration-underline">USE OF LINKS</b>
              </p>
              <p>
                The Services may contain links to other websites and services,
                which are developed, sponsored and/or maintained by third
                parties.
              </p>
              <p>
                We do not review, monitor, operate or control any such third
                party website/services accessible through these links, and is
                not responsible for the content available on or through such
                third party websites/services. By providing access to the linked
                websites/services, Arena Laundry is not recommending or
                endorsing the products or services provided by the sponsor or
                owner of those websites/services. We make no guarantees,
                representations or warranties as to, and shall have no liability
                for, any electronic content delivered by any third party,
                including, without limitation, the accuracy or subject matter of
                any electronic content, or the use of any personal information
                you provide to any such website/services. You acknowledge and
                agree that use of such links is entirely at your own risk. We
                reserve the right to discontinue links to any other website at
                any time and for any reason.
              </p>
              <p>
                <b className="text-decoration-underline">INDEMNITY</b>
              </p>
              <p>
                You agree to indemnify and hold Arena Laundry and its officers,
                directors, employees and agents, harmless from any and all
                claims, demands, losses, liabilities, and expenses (including
                attorneys’ fees), arising out of or in connection with: (i) your
                use of the Services; (ii) your breach or violation of any of
                this Agreement; (iii) Arena Laundry’s use of your User Content;
                or (iv) your violation of the rights of any third party,
                including Third Party Contractors.
              </p>
            </li>
            <li>
              <b>MISCELLANEOUS GOVERNING LAW</b>
              <br />
              <br />
              <p>
                You acknowledge and agree that your access to and use of the
                Services is subject to all applicable international, federal,
                state and local laws and regulations. The terms, conditions and
                policies contained in this Agreement shall be governed by and
                construed in accordance with the laws of the State of
                Connecticut, without regard to any principles of conflicts of
                law, and all claims, disputes or disagreements which may arise
                out of the interpretation, performance or in any way relating to
                your use of the Services, shall be submitted exclusively to the
                jurisdiction of the State or federal courts located in the
                County and State of Connecticut. You acknowledge and agree that
                you will irrevocably consent and submit to the exclusive
                personal jurisdiction of those courts for the purpose of
                litigating any such action; and you will irrevocably waive any
                jurisdictional, venue or inconvenient forum objections to such
                court. Any waiver by Arena Laundry of any provision of this Agreement must
                be in writing.
              </p>
              <p>
                <b className="text-decoration-underline">NOTICE</b>
              </p>
              <p>
              Arena Laundry may give notice by means of a general notice on the
                Services, electronic mail to your email address in your Account,
                or by written communication sent by first class mail or pre-paid
                post to your address in your Account. Such notice shall be
                deemed given upon the expiration of 48 hours after mailing or
                posting (if sent by first class mail or pre-paid post) or 12
                hours after sending (if sent by email).
              </p>
              <p>
                <b className="text-decoration-underline">GENERAL</b>
              </p>
              <p>
                You may not assign these Terms without Arena Laundry’s prior written
                approval. Arena Laundry may assign this Agreement without your consent to:
                (i) a subsidiary or affiliate; (ii) an acquirer of Arena Laundry equity,
                business or assets; or (iii) a successor by merger. Any
                purported assignment in violation of this section shall be void.
                No joint venture, partnership, employment, or agency
                relationship exists between you, Arena Laundry or any Third Party
                Contractor as a result of this Agreement or use of the Services.
                If any provision of this Agreement is held to be invalid or
                unenforceable, such provision shall be struck and the remaining
                provisions shall be enforced to the fullest extent under law.
                Our failure to enforce any right or provision in this Agreement
                shall not constitute a waiver of such right or provision unless
                acknowledged and agreed to by Arena Laundry in writing.
              </p>
            </li>
          </ol>
        </div>
      </div>
      <Footer />
    </>
  );
}

export default Terms;
